RedHatInsights/topological_inventory-sync

Gemfile
core in Gemfile is linked to non-existing branch, switched to ManageIQ's master
=> Replaced gemfile's nonexisting branch

bin/topological-inventory-inventory-upload, bin/topological-inventory-inventory-upload-validator, lib/topological_inventory/sync/inventory_upload_validator_worker.rb, lib/topological_inventory/sync/inventory_upload_worker.rb, lib/topological_inventory/sync/worker.rb
This adds a simple validation service and a processing service to handle topological-inventory and/or cfme payloads sent to the upload service.
=> Add two simple services to process topological-inventory payloads from the upload service

Gemfile, bin/topological-inventory-inventory-upload-validator, lib/topological_inventory/sync/inventory_upload_validator_worker.rb
Payload from InsightsUpload service has to be validated first. 
I'm using request metadata to check if schema class exists (using the same approach as `Persister::Worker`).
---
---
**On localhost:**
Sample payload:
```
plain_rh_identity="{\"identity\":{\"account_number\":\"test-mock\"}, \"internal\": {\"org_id\": \"54321\"}}"
export X_RH_IDENTITY=$(echo ${plain_rh_identity} | base64 --wrap=0)
curl -vvvv -H "x-rh-identity: ${X_RH_IDENTITY}" -F "upload=@README.md;type=application/vnd.redhat.topological-inventory.mock" -F metadata="{\"schema\": {\"name\": \"Default\"}}" -H "x-rh-insights-request-id: 123" localhost:8888/api/ingress/v1/upload
```
_Note: substitute @README.md with existing file_
Running insights-upload with params:
`INVENTORY_URL="http://localhost:8888/api/hosts" …
=> Payload validation against Schema class

bin/topological-inventory-inventory-upload
Allow building the ingress-api url from default env vars provided to the
service.
=> Fix the handling of ingress_api env vars

lib/topological_inventory/sync/inventory_upload/processor_worker.rb
Fixes the following exception:
```
uninitialized constant TopologicalInventoryIngressApiClient::SaveInventory (NameError)
/opt/topological_inventory-sync/lib/topological_inventory/sync/inventory_upload/processor_worker.rb:125:in `ingress_api_sender'
/opt/topological_inventory-sync/lib/topological_inventory/sync/inventory_upload/processor_worker.rb:94:in `send_to_ingress_api'
/opt/topological_inventory-sync/lib/topological_inventory/sync/inventory_upload/processor_worker.rb:50:in `process_inventory'
/opt/topological_inventory-sync/lib/topological_inventory/sync/inventory_upload/processor_worker.rb:35:in `perform'
/opt/topological_inventory-sync/lib/topological_inventory/sync/worker.rb:25:in `block in run'
```
=> Fix uninitialized constant SaveInventory

lib/topological_inventory/sync/inventory_upload/parser.rb, lib/topological_inventory/sync/inventory_upload/processor_worker.rb, lib/topological_inventory/sync/inventory_upload/validator_worker.rb
Yield each inventory in a tgz file to allow for support of multiple json
files per tgz payload.
=> Allow for multiple files per payload

lib/topological_inventory/sync/inventory_upload/processor_worker.rb, spec/topological_inventory/sync/inventory_upload/processor_worker_spec.rb
We are using a TopologicalInventoryIngressApi::Inventory object when
parsing cfme inventory.  Deserialize the json payload to this object
type for consistency.
Depends: ~~https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/pull/43~~
=> Deserialize topo inventory for consistency

Gemfile, lib/topological_inventory/sync/sources_sync_worker.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
Fix sources-sync now that tenant is no longer in the payload returned
for a source by the sources-api.
=> Tenant was removed from the sources payload

Gemfile, lib/topological_inventory/sync/sources_sync_worker.rb
The ManageIQ::API::Common gem has an engine that depends on rails, this
is not a rails app so just decode the headers manually.
```
== Writing encryption key ==
--
  | == Checking topological-inventory-postgresql:5432 status ==
  | topological-inventory-postgresql:5432 - accepting connections
  | /usr/local/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-common-dac4157d50ff/lib/manageiq/api/common/engine.rb:4:in `<module:Common>': uninitialized constant Rails (NameError)
  | from /usr/local/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-common-dac4157d50ff/lib/manageiq/api/common/engine.rb:3:in `<module:API>'
  | from /usr/local/lib/ruby/gems/2.4.0/bundler/gems/manageiq-api-common-dac4157d50ff/lib/manageiq/api/common/engine.rb:2:in `<module:ManageIQ>'
  | from …
```
=> Don't use ManageIQ::API::Common without Rails

lib/topological_inventory/sync/inventory_upload/processor_worker.rb
Parse a number of "extra" properties coming from MIQ that don't map well
to real attributes but are needed for migration analytics.
=> Parse extra properties from MIQ

lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/payload/cfme.rb, spec/topological_inventory/sync/inventory_upload/payload/cfme_spec.rb, spec/topological_inventory/sync/inventory_upload/payload_spec.rb
When the source-api-client is handling an unsuccessful API call it
doesn't return the error code but instead raises an exception.  This was
making it extremely difficult to figure out why something was failing
because all we got was "400 Bad Request" (the Exception Class) not _why_
it was a bad request (duplicate source_name).
=> Improve error logging when hitting sources-api

bin/topological-inventory-sources-sync
Fix an undefined method logging caused by not requiring the module.
https://github.com/ManageIQ/topological_inventory-core/pull/147 started exposing this
=> Require topological_inventory core logging

lib/topological_inventory/sync/inventory_upload/parser/cfme.rb, spec/topological_inventory/sync/inventory_upload/parser/cfme_spec.rb
I saw `nils` in  `Hardware#memory_by`  in testing DB - so when the nil would be propagated here it will throw error because there is `*` operation.
@miq-bot assign @agrare
=> Set Hardware#memory_by to 0 when value is missing in Parser:Cfme

lib/topological_inventory/sync/sources_sync_worker.rb, lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
Use cache_with_timeout for supported application types so that any
updates while the sources-sync worker is running will be picked up
within 5 minutes
=> Use cache_with_timeout for application_types

lib/topological_inventory/sync/inventory_upload/payload/cfme.rb
Fix an issue with uploading ManageIQ::Providers::Redhat::InfraManager
sources from cloudforms.
https://github.com/ManageIQ/sources-api/blob/master/db/seeds/source_types.rb#L75
=> The RHV source_type.name is ovirt not rhv

lib/topological_inventory/sync/inventory_upload/parser/cfme.rb
RHV doesn't set host_storage.ems_ref like vmware so we have to get it
from host_storage.ems_ref || storage.ems_ref
Depends on: https://github.com/ManageIQ/topological_inventory-api/pull/242
=> Get datastore ems_ref from host_storage or storage

lib/topological_inventory/sync/inventory_upload/parser/cfme.rb, spec/helpers/cfme_inventory.json
The ems_ref on the datastore_mount is for the storage not the host.
Fixes:
```
Error message: Bad Request. Body: {"message":"required parameters source_ref not exist in #/components/schemas/Datastore/allOf/1","error_code":"OpenAPIParser::NotExistRequiredKey"}
```
When saving inventory
=> Fix ovirt datastore parsing

Gemfile, lib/topological_inventory/sync/inventory_upload/parser/cfme.rb, lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/processor_worker.rb
=> Fix inventory_upload to use providers-common

lib/topological_inventory/sync/api_client.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
We need to set the user.is_org_admin attribute for API calls to
sources-api otherwise a missing key will trigger an unauthorized error
even if the API call is readonly.
=> Set is_org_admin for API calls to sources

lib/topological_inventory/sync/inventory_upload/processor_worker.rb, lib/topological_inventory/sync/inventory_upload/validator_worker.rb, spec/helpers/inventory_upload_helper.rb, spec/topological_inventory/sync/inventory_upload/validator_worker_spec.rb
The Payload Tracker is transitioning to using the new "request_id" terminology instead of the legacy "payload_id." This renames that field.
=> Update payload_id to request_id

lib/topological_inventory/sync/iterator.rb, lib/topological_inventory/sync/sources_sync_worker.rb, spec/topological_inventory/sync/iterator_spec.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
Initial sync is able to manage only first 100 (default limit) sources of each tenant.
This PR adds Iterator for pagination
---
[TPINVTRY-1061](https://projects.engineering.redhat.com/browse/TPINVTRY-1061)
=> Sources Sync: Added pagination to api calls

lib/topological_inventory/sync/configuration.rb, lib/topological_inventory/sync/host_inventory_response_worker.rb, lib/topological_inventory/sync/host_inventory_sync_worker.rb, spec/topological_inventory/sync/host_inventory_response_worker_spec.rb, spec/topological_inventory/sync/host_inventory_sync_worker_spec.rb
Description
---
Moving the host-inventory VM creation call from HTTP to Kafka. 
This PR is based on https://projects.engineering.redhat.com/browse/TPINVTRY-874. 
Testing
---
1) `insights-host-inventory/app/config.py:44` -  kafka port change
* before: `self.bootstrap_servers = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "localhost:29092")`
* after:   `self.bootstrap_servers = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")`
2) `insights-host-inventory/app/config.py:44` - response topic change
* There are three types of events HBI produces: `created`, `updated` and `delete`. All the events are sent as kafka messages to the `platform.inventory.events` kafka topic as you can find in the [documentation](https://platform-docs.cloud.paas.psi.redhat.com/backend/inventory.html#event-inter …
=> Switch host-inventory-sync to post HBI to kafka rather than HTTP

lib/topological_inventory/sync/metrics/sources_sync.rb
Fixes #72 
There is `private` in metrics class, IDK how it should pass through tests, anyway QA pods are failing
---
[RHCLOUD-9939](https://issues.redhat.com/browse/RHCLOUD-9939)
=> Sources Sync Metrics fix

bin/topological-inventory-sources-sync
https://issues.redhat.com/browse/RHCLOUD-10690
Adding a new CLI option `--sync-and-exit` so that we can just run a one-time full sync. This is for the new CronJob we're creating.
=> Add --sync-and-exit option for one-time syncing

README.md
Travis migrated from URL travis-ci.org -> travis-ci.com.
This PR is based on https://github.com/RedHatInsights/topological_inventory-api/issues/334 issue.
=> Update travis URL in README file.

lib/topological_inventory/sync/worker.rb
`group_ref` in messaging_client configuration is useless.
Moreover it started to crash on localhost with:
```
/home/mslemr/.rvm/gems/ruby-2.6.6@tp-inv/gems/rdkafka-0.8.0/lib/rdkafka/config.rb:173:in `block (2 levels) in native_config': No such configuration property: "group_ref" (Rdkafka::Config::ConfigError)
```
Also present in (not all) other repos
=> Remove unrecognized group_ref from messaging client

lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
404 error can be caused by cascade delete of Source, when Application.destroy is processed and Source doesn't exist.
It's not an error of sync worker so it should be skipped without logs and metrics update
---
[RHCLOUD-12782](https://issues.redhat.com/browse/RHCLOUD-12782)
=> Sources Sync: Omit 404 errors
