RedHatInsights/topological_inventory-sync

Gemfile, lib/topological_inventory/sync/inventory_upload_validator_worker.rb, spec/topological_inventory/sync/inventory_upload_validator_worker_spec.rb
Initial attempt at using streaming/chunked methods for every layer of accessing the payload to verify.
=> Use streaming json/tar/gz/http for parsing payload

bin/topological-inventory-inventory-upload, lib/topological_inventory/sync/inventory_upload/processor_worker.rb, lib/topological_inventory/sync/inventory_upload/validator_worker.rb, lib/topological_inventory/sync/sources_sync_worker.rb, lib/topological_inventory/sync/worker.rb, spec/helpers/inventory_upload_helper.rb, spec/topological_inventory/sync/inventory_upload/processor_worker_spec.rb, spec/topological_inventory/sync/inventory_upload/validator_worker_spec.rb
InventoryUpload Processor Worker receives payload with link to tgz file from kafka topic 'platform.upload.available'.
It checks if source type given in file exists in sources db and then finds or creates source.
---
**Issue**: https://github.com/ManageIQ/topological_inventory-sync/issues/9
=> Create source from insights-upload payload

Gemfile, bin/topological-inventory-inventory-upload, lib/topological_inventory/sync/inventory_upload/processor_worker.rb, spec/topological_inventory/sync/inventory_upload/processor_worker_spec.rb
Now working only for "Default" schema.
---
**Issue** #9
=> Sending InsightsUpload file to Ingress API

spec/topological_inventory/sync/inventory_upload/processor_worker_spec.rb, spec/topological_inventory/sync/inventory_upload/validator_worker_spec.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
=> Fix specs for manageiq-messaging v0.1.5 changes

lib/topological_inventory/sync/worker.rb
Exceptions weren't being logged to kibana which makes it very difficult
to determine what is wrong.
https://projects.engineering.redhat.com/browse/TPINVTRY-467
=> Improve exception logging while processing messages

lib/topological_inventory/sync/inventory_upload/processor_worker.rb, lib/topological_inventory/sync/inventory_upload/validator_worker.rb, spec/helpers/cfme_inventory.json, spec/helpers/inventory_upload_helper.rb, spec/topological_inventory/sync/inventory_upload/validator_worker_spec.rb
Conditionally process CFME and Topological Inventory schema.  First pass automatically creates the source when the payload is pushed and parses out vms.
=> Initial handling of CFME schema, create source

lib/topological_inventory/sync/inventory_upload/processor_worker.rb
This was causing a persister error on the RefreshStatePartUuid.uuid non-null constraint
=> Fix missing refresh_state_part_uuid

lib/topological_inventory/sync/inventory_upload/processor_worker.rb, spec/helpers/cfme_inventory.json
In addition to VMs, parse Hosts and Clusters
=> Parse hosts and clusters

lib/topological_inventory/sync/inventory_upload/processor_worker.rb
Parse CFME Storages into topological inventory Datastores
Depends on:
https://github.com/ManageIQ/topological_inventory-ingress_api/pull/62
https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/pull/44
=> Parse Datastores from CFME Storages

lib/topological_inventory/sync/inventory_upload/processor_worker.rb, spec/helpers/cfme_inventory.json
Depends:
https://github.com/ManageIQ/topological_inventory-api/pull/218
=> Cross link vms to hosts, hosts to clusters, and hosts to datastores

lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/processor_worker.rb, lib/topological_inventory/sync/inventory_upload/validator_worker.rb, spec/topological_inventory/sync/inventory_upload/processor_worker_spec.rb, spec/topological_inventory/sync/inventory_upload/validator_worker_spec.rb
Refactoring in preparation for future changes to parsing.
=> Move existing InventoryUpload::Parser class to Payload

lib/topological_inventory/sync/inventory_upload/parser.rb, lib/topological_inventory/sync/inventory_upload/parser/cfme.rb, lib/topological_inventory/sync/inventory_upload/payload/cfme.rb
Move parsing into its own class to cleanup the payload processor
Depends on: ~~https://github.com/ManageIQ/topological_inventory-sync/pull/31~~
=> Refactor CFME Payload Parsing

lib/topological_inventory/sync/inventory_upload/payload.rb
=> Log error when saving inventory thru ingress call in Payload

lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/payload/cfme.rb, lib/topological_inventory/sync/inventory_upload/payload/default.rb, lib/topological_inventory/sync/sources_sync_worker.rb, lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/inventory_upload/payload/cfme_spec.rb
CFME Source needs topological-inventory application to be synchronized to topological-inventory database
=> Find/Create application together with CFME Source

lib/topological_inventory/sync/sources_sync_worker.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
Test the case where we need to create a source and when we need to delete a source on initial startup
=> Add specs for SourcesSync#initial_sync

Gemfile, bin/topological-inventory-inventory-upload, lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/payload/cfme.rb, spec/topological_inventory/sync/inventory_upload/payload/cfme_spec.rb
=> Wait for creation of source in topology inventory before sending inventory

lib/topological_inventory/sync.rb, lib/topological_inventory/sync/api_client.rb, lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/inventory_upload/payload/cfme_spec.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
Move creation of api client objects to one file.
=> Refactor api clients

lib/topological_inventory/sync/inventory_upload/validator_worker.rb
If a non tar.gz file was passed or the tar.gz doesn't container a json
file improve the error message shown.
=> Improve the error message for invalid files

lib/topological_inventory/sync/inventory_upload/payload.rb, lib/topological_inventory/sync/inventory_upload/payload/cfme.rb, lib/topological_inventory/sync/inventory_upload/payload/default.rb, spec/topological_inventory/sync/inventory_upload/payload/cfme_spec.rb, spec/topological_inventory/sync/inventory_upload/payload_spec.rb
TPINVTRY-632
WIP:
I needed to change parameter list of `find_or_create_source ` method first.(first commit)
@miq-bot assign @agrare
=> [WIP] Set read only flag for sources from CFME

lib/topological_inventory/sync/sources_sync_worker.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
TPINVTRY-772
Sync has error in `Application.create` and `Application.destroy` events.
for _Application.create_:
* **now**: adding two supported applications for Source crashes 
* **expected**: no change
for _Application.destroy_:
* **now**: removing any application when other supported application still exists deletes Source from Topological DB
* **expected**: Source is deleted when last supported application for Source is removed.
=> Sync:Fixed Application.create/destroy events

Gemfile
=> ManageIQ -> RedHatInsights in gemfile

Gemfile, bin/topological-inventory-host-inventory-sync, lib/topological_inventory/sync/application_metrics.rb, lib/topological_inventory/sync/host_inventory_sync_worker.rb, spec/spec_helper.rb, spec/topological_inventory/sync/host_inventory_sync_spec.rb
Joining this repo and https://github.com/RedHatInsights/topological_inventory-host_inventory_sync
**dependent**: https://github.com/RedHatInsights/e2e-deploy/pull/1379
=> Move Host inventory sync worker to this repo

Gemfile
=> Gemfile update (Hakiri warning)

.codeclimate.yml, .rubocop.yml, .rubocop_cc.yml, .travis.yml, Gemfile
Setting up the simplecov/codeclimate for sync repository.
* Updated files:
`Gemfile`, `.travis.yml`
* New files:
`.codeclimate.yml`, `.rubocop.yml`, `.rubocop_cc.yml`, `.rubocop_local.yml`
=> Simplecov-Codeclimate setup.

bin/topological-inventory-sources-sync, lib/topological_inventory/sync/metrics.rb, lib/topological_inventory/sync/metrics/sources_sync.rb, lib/topological_inventory/sync/sources_sync_worker.rb, lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/metrics_spec.rb, spec/topological_inventory/sync/sources_sync_worker_spec.rb
**Issue**: https://github.com/RedHatInsights/topological_inventory-api/issues/320
Added custom metrics:
* topological_inventory_sources_sync_errors_total
* topological_inventory_sources_sync_sources_created
* topological_inventory_sources_sync_sources_destroyed
=> Sources Sync custom metrics

bin/topological-inventory-host-inventory-sync, bin/topological-inventory-sources-sync, lib/topological_inventory/sync/host_inventory_response_worker.rb, lib/topological_inventory/sync/host_inventory_sync_worker.rb, lib/topological_inventory/sync/metrics.rb, lib/topological_inventory/sync/metrics/host_inventory_sync.rb, lib/topological_inventory/sync/metrics/sources_sync.rb, lib/topological_inventory/sync/sources_sync_worker.rb, lib/topological_inventory/sync/worker.rb, spec/topological_inventory/sync/host_inventory_response_worker_spec.rb, spec/topological_inventory/sync/host_inventory_sync_worker_spec.rb, spec/topological_inventory/sync/metrics_spec.rb
**Issue** https://github.com/RedHatInsights/topological_inventory-api/issues/320
Metrics for host inventory sync + updates for sources sync metrics
---
[RHCLOUD-9939](https://issues.redhat.com/browse/RHCLOUD-9939)
[RHCLOUD-9940](https://issues.redhat.com/browse/RHCLOUD-9940)
=> Custom metrics for host inv sync + sources sync metrics update
